### ISSUE TITLE
Hosts causing crashes

### ISSUE THREAD

**Issue by ObserverHerb** [EngineeringDeck/Celeste#35]
Attagoat and boobtoob both crashed Celeste by hosting the Observeration Deck. Unfortunately, it crashes before it logs the message, so I'm not sure just yet how to modify the parser to handle it.

**Comment by herbmillerjr** [comment]
Solving this may be the solution to #17

**Comment by herbmillerjr** [comment]
I wonder if this is still a thing since the rewrite.

**Comment by herbmillerjr** [comment]
Finally found examples in the logs (now that, because of the rewrite, it no longer crashes).

`./20211201.log::jtv!jtv@jtv.tmi.twitch.tv PRIVMSG observerherb :Attagoat is now hosting you.`

`./20210923.log::jtv!jtv@jtv.tmi.twitch.tv PRIVMSG observerherb :CalyxCreative is now hosting you.`

At first glance I'm going to say the lack of tags or badges is probably the problem.

**Comment by herbmillerjr** [comment]
Might be affected by #75.

**Comment by ObserverHerb** [comment]
Hosts are no longer a thing.
