### ISSUE TITLE
Add !exactfigures command

### ISSUE THREAD

**Issue by ObserverHerb** [EngineeringDeck/Celeste#60]
One of Celeste's roasts mentions exact figures regarding my total streaming hours. Ariickk suggested adding a command to actually pull those figure. The Twitch API probably provides all of this and it would be a fun one to do on stream.

**Comment by herbmillerjr** [comment]
Contrary to what I believed, Twitch does not provide an API endpoint that returns hours streamed, neither total overall or total for any given stream. This link (https://discuss.dev.twitch.tv/t/fetch-accumulated-user-stream-monthly-total/18492) leads me to believe that the Get Streams endpoint at one time logged stop times, but now it only returns active streams with no stop times (I think?).

Perhaps this is instead a good opportunity to fix the `!uptime` command and have it return the uptime of *the stream* rather than Celeste.

**Comment by herbmillerjr** [comment]
Channel Analytics has my total hours for each month for the entire history of the channel, so I could keep that total updated, then add the current stream's hours to it.
